---
- hosts: tag_Module_5
  user: ec2-user
  become: true
  tasks:
    - name: install python3 dev
      package:
        name: python3-devel
        state: present
    - name: install postgres
      package:
        name: postgresql
        state: present
    - name: install tree
      package:
        name: tree
        state: present
 

#cannot find host for some reason... tag not working....
#need to add all dependencies for server to run
#postgres, python3 devel, psycopg2, boto3, flask, nginx, git, tree
