---
- hosts: localhost
  tasks:
    - name: rds restore
      rds:
        command: restore
        instance_name: Module5
        snapshot: ansible-snapshot
        region: 'us-west-1'
        db_engine: postgres
        instance_type: db.t2.micro
        username: image-gallery
